### ISSUE TITLE
memory requirement for DeltaCNN

### ISSUE THREAD

**Issue by kai981** [facebookresearch/DeltaCNN#13]
Hi! I am currently trying to find out the additional memory requirement needed for DeltaCNN. 

Just to clarify so that I am going in the right direction. The extra memory would be from the single channel masks for every layer in the model (which are propagated together with the output feature maps), as well as the buffers for the nonlinear layers. The buffers would be the same size as the feature maps in the respective layer. Nonlinear layers like sparsify, densify, pooling require one extra buffer, whereas activation requires two extra buffers. 
So for instance, if the input is (1,3,640,640), then sparsify layer would require a buffer storing this same shape of (1,3,640,640) is that right? So the extra parameters stored for the first sparsify layer alone is already 1,228,800 pixels? 

Thank you!

**Comment by dabeschte** [comment]
Hey!
Yes, that's mostly correct. The memory for the layers is correct as you described it. But the memory for the mask can more or less be ignored since the masks are only used between two layers and discarded afterwards.
An easy was to measure memory overhead is to store the shape of all buffers used in deltacnn. Since we only use buffers in a few layers, that should be easy to add into sparse_layers.py

**Comment by dabeschte** [comment]
May I ask what you are working on? You seem to analyse deltacnn quite thoroughly :)

**Comment by kai981** [comment]
Thanks for the super quick reply! :))
I am working on a school project actually, regarding efficient video inference method. I was looking at skip-conv previously and saw your comment, so I came over! HAHA
