### ISSUE TITLE
Issue with threshold tuning 

### ISSUE THREAD

**Issue by kai981** [facebookresearch/DeltaCNN#9]
Hi, I am back again :) 

I am trying to do some threshold tuning for my model, but encountered the problem that `DCThreshold.t ` is empty after running the model. It's odd because I have checked that is it running in deltacnn mode, so it should at least have the layers with default threshold 0 right? 
Any idea what could be the problem? Or suggestion on how I should debug the issue? (other checks?) 

Thank you!

**Comment by dabeschte** [comment]
Hey!
This sounds strange. And I don't really know how this can happen except by manually resetting DCThreshold which you should actually never need to do.
Can you set a breakpoint here and make sure that the code continues and actually sets the layer's threshold? https://github.com/facebookresearch/DeltaCNN/blob/81dd82f4217bba945edbe0647f111d89afc76fee/src/deltacnn/sparse_layers.py#L1380

One other problem could be that you have two different installations of DeltaCNN and import different versions in different files.
E.g. importing the sparse_layers.py once from the global installation and once from a subdirectory

**Comment by kai981** [comment]
Hi! some updates and new questions 

I have managed to resolve the issue, realized that I do have different installations of deltacnn, so fixing that solved the problem. 

some new questions: 
1. I realized that because I am using dense_out=True for a conv layer in squeeze and excite, so thresholding applied to that conv layer as well. May I know why thresholding is also applied to conv layer with dense_out=True, other than for activation layers?
2. Would you suggest that I set the sparsify to threshold=0.5, dilation=7 and tune the rest of the layers, or leave the sparsify layer with threshold=0, dilation=1, tune the rest of layers and tune the sparsify layer last? 

Thank you!

**Comment by dabeschte** [comment]
ok, good to know.

1: No worries, thresholding is not applied when you set dense_out=True. The only reason a threshold still gets created there is because I accidently registered thresholds in earlier versions when dense_out was set to True. But since I wanted to reuse thresholds that I tuned before that time, I kept that behaviour the same to make sure that everything is backwards compatible.
But you are right, it does not make sense to keep this around in the public release anymore. Will remove it right away. Thanks for letting me know!

2: I would suggest that you keep all layers at threshold=0 and manually try out different thresholds / dilation values for the sparsify layer first. then continue with the remaining layers. threshold=0.5, dilation=7 is a good start for imagenet-normalized images when applied to the MOT16/17 dataset
